"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RECOVERABLE_MESSAGE = exports.MESSAGE_ATTACHMENT_JOIN = exports.MESSAGE = exports.CHAT_MESSAGE_JOIN = exports.CHAT_HANDLE_JOIN = exports.CHAT = exports.ATTACHMENT = exports.HANDLE = void 0;
exports.HANDLE = 'handle';
exports.ATTACHMENT = 'attachment';
exports.CHAT = 'chat';
exports.CHAT_HANDLE_JOIN = 'chat_handle_join';
exports.CHAT_MESSAGE_JOIN = 'chat_message_join';
exports.MESSAGE = 'message';
exports.MESSAGE_ATTACHMENT_JOIN = 'message_attachment_join';
exports.RECOVERABLE_MESSAGE = 'chat_recoverable_message_join';
